//****************** Generated by UpShift Transformer Logic ******************/

package com.cognizant.cde.fego.samples.ProductAPIResilience4J;

import org.testng.Assert;
import org.testng.annotations.*;

public class TestNgStarter {

    @Test
    public void sampleTest1() {
        Assert.assertTrue(10 % 2 == 0);
    }

    @Test(dependsOnMethods = { "sampleTest1" })
    public void sampleTest2() {
        Assert.assertTrue(11 % 2 == 1);
    }

    @Test(enabled = false)
    public void sampleTest3() {
        Assert.assertTrue(10 % 2 == 0);
    }

    @Test(dataProvider = "numbers")
    public void sampleTest4(Integer number, boolean expected) {
        Assert.assertEquals(expected, number % 2 == 0);
    }

    @DataProvider(name = "numbers")
    public static Object[][] setOfNumbers() {
        return new Object[][] { { 1, false }, { 2, true }, { 3, false }, { 4, true }, { 5, false } };
    }

    @BeforeClass
    public void testClassSetup() {
    // This method will be invoked before all other methods in the test class
    }

    @AfterClass
    public void testClassTearDown() {
    // This method will be invoked after all the other methods in the test class
    }

    @BeforeMethod
    public void testMethodSetup() {
    // This class will be invoked before every test method
    }

    @AfterMethod
    public void testMethodTearDown() {
    // This class will be invoked after every test method
    }

    @BeforeGroups
    public void testGroupSetup() {
    // This class will be invoked before every test group
    }

    @AfterGroups
    public void testGroupTearDown() {
    // This class will be invoked after every test group
    }

    @BeforeSuite
    public void testSuiteSetup() {
    // This class will be invoked before every test suites
    }

    @AfterSuite
    public void testSuiteTearDown() {
    // This class will be invoked after every test suite
    }
}
